### PR TITLE
Add support of multiple GNSS recievers in gps_dump messages

### PR DESCRIPTION
**Pull request by roman-dvorak**
Hi,

I have opened PR https://github.com/PX4/PX4-Autopilot/pull/16258 in PX4 firmware, that adds support of gps_dump from multiple GNSS recievers. This PR adds support for multiple receivers in the `gps_dump`.

I added a new launch parameter `-i` that specifies the receiver instance. `-i 0` (default) exports dump of main (first) reciever. 

I have also reneamed original parametr `-i` to `-x`. It is parametr that: 'Ignore string parsing exceptions'

### CODE REVIEW

**Review by bkueng — COMMENTED** [review]
Thanks, can you fix the remaining CI issues in that script:
```
pyulog/extract_gps_dump.py:35:0: C0301: Line too long (106/100) (line-too-long)
pyulog/extract_gps_dump.py:62:8: R1722: Consider using sys.exit() (consider-using-sys-exit)
pyulog/extract_gps_dump.py:70:8: R1722: Consider using sys.exit() (consider-using-sys-exit)
```

**Comment by roman-dvorak** [comment]
@bkueng 
Yes, I will solve it today, later.

**Comment by roman-dvorak** [comment]
These tasks issues are resolved. But it still contains some bugs. I think unrelated to my PR. I can fix them in the next PR

> Thanks, can you fix the remaining CI issues in that script:
> 
> ```
> pyulog/extract_gps_dump.py:35:0: C0301: Line too long (106/100) (line-too-long)
> pyulog/extract_gps_dump.py:62:8: R1722: Consider using sys.exit() (consider-using-sys-exit)
> pyulog/extract_gps_dump.py:70:8: R1722: Consider using sys.exit() (consider-using-sys-exit)
> ```

**Review by bkueng — APPROVED** [review]
> I think unrelated to my PR. I can fix them in the next PR

Yes they are unrelated, you're welcome to fix them. This typically happens when pylint updates and adds new checks.

**Pull request merged**
