### PR TITLE
Create python package/ standardize install.

### PR DESCRIPTION
**Pull request by jgoppert**
To fit in well with other python packages such as px4tools I think it is best if we make this a full package. I also think we should try to get it on conda-forge so we can have it built and tested on all platforms.

### CODE REVIEW

**Comment by bkueng** [comment]
Very nice! This will make it a lot easier to use. I have few things that I think need changing:
- rename the scripts from `pyulog_params` to `ulog_params`. I don't think it will interfere, or do you have any reasons against it?
- add instructions to README how to install with symlinks for easier devel
- Write better, more precise commit messages
- Reduce the size of the ulog sample to ~1MB. Should be enough for testing and I'd like to avoid blowing up the git repo size early on.

Will you take care of pushing it to PyPI?

**Comment by jgoppert** [comment]
Sounds good, I will work on those items and push it to pypi. I would also like to add it to conda-forge as that is my main deployment and ci mechanism for px4tools.

**Comment by jgoppert** [comment]
@bkeung, what are you envisioning with regard to the symlinks for development?

**Comment by bkueng** [comment]
Just tell me if you need anything more for conda-forge.

Well, until now I was always able to work within the repo, now I require an install step to use the scripts. But what I found is that you can do `pip install -e .`, which installs it but with symlinks to the repo, so you can still directly edit the code. I'm not sure if that's the standard python way to do it.

**Comment by jgoppert** [comment]
@bkueng Ready for review.

**Comment by jgoppert** [comment]
@bkueng pypi is up: https://pypi.python.org/pypi/pyulog/0.0.1

You can install with pip now:

```bash
pip install pyulog
```

**Comment by bkueng** [comment]
Thanks!

**Pull request merged**
